package com.dbtraining.reconx.service;

import com.dbtraining.reconx.domain.Counterparty;
import com.dbtraining.reconx.domain.Instrument;
import com.dbtraining.reconx.domain.Trade;
import jakarta.persistence.EntityManager;
import jakarta.persistence.EntityManagerFactory;
import jakarta.persistence.EntityTransaction;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.autoconfigure.EnableAutoConfiguration;
import org.springframework.boot.autoconfigure.domain.EntityScan;
import org.springframework.boot.test.autoconfigure.orm.jpa.DataJpaTest;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;
import org.springframework.context.annotation.Import;
import org.springframework.data.jpa.repository.config.EnableJpaAuditing;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.test.context.TestPropertySource;

import java.math.BigDecimal;
import java.time.LocalDate;
import java.util.List;

import static org.assertj.core.api.Assertions.assertThat;

@DataJpaTest
@TestPropertySource(properties = {
        "spring.jpa.hibernate.ddl-auto=none",
        "spring.jpa.properties.hibernate.hbm2ddl.auto=none"
})
@Import(TradeHistoryService.class)
class TradeHistoryServiceTest {

    @Autowired
    private TradeHistoryService tradeHistoryService;

    @Autowired
    private EntityManagerFactory entityManagerFactory;

    @Autowired
    private JdbcTemplate jdbcTemplate;

    @org.junit.jupiter.api.BeforeEach
    void setUpSchema() {
        jdbcTemplate.execute("DROP TABLE IF EXISTS trades_aud");
        jdbcTemplate.execute("DROP TABLE IF EXISTS instruments_aud");
        jdbcTemplate.execute("DROP TABLE IF EXISTS counterparty_aud");
        jdbcTemplate.execute("DROP TABLE IF EXISTS trades");
        jdbcTemplate.execute("DROP TABLE IF EXISTS instruments");
        jdbcTemplate.execute("DROP TABLE IF EXISTS counterparty");
        jdbcTemplate.execute("DROP TABLE IF EXISTS revinfo");

        jdbcTemplate.execute("CREATE TABLE revinfo (rev BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, revtstmp BIGINT NOT NULL)");
        jdbcTemplate.execute("CREATE TABLE counterparty (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, name VARCHAR(255))");
        jdbcTemplate.execute("CREATE TABLE counterparty_aud (id BIGINT NOT NULL, rev BIGINT NOT NULL, revtype SMALLINT NOT NULL, name VARCHAR(255), PRIMARY KEY (id, rev), CONSTRAINT fk_counterparty_aud_rev FOREIGN KEY (rev) REFERENCES revinfo (rev))");
        jdbcTemplate.execute("CREATE TABLE instruments (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, symbol VARCHAR(20) NOT NULL UNIQUE, name VARCHAR(200) NOT NULL, asset_class VARCHAR(20) NOT NULL, currency VARCHAR(3) NOT NULL, metadata VARCHAR(2000))");
        jdbcTemplate.execute("CREATE TABLE instruments_aud (id BIGINT NOT NULL, rev BIGINT NOT NULL, revtype SMALLINT NOT NULL, symbol VARCHAR(20), name VARCHAR(200), asset_class VARCHAR(20), currency VARCHAR(3), metadata VARCHAR(2000), PRIMARY KEY (id, rev), CONSTRAINT fk_instruments_aud_rev FOREIGN KEY (rev) REFERENCES revinfo (rev))");
        jdbcTemplate.execute("CREATE TABLE trades (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, trade_ref VARCHAR(30) NOT NULL UNIQUE, counterparty_id BIGINT NOT NULL, instrument_id BIGINT NOT NULL, quantity DECIMAL(18,4) NOT NULL, price DECIMAL(18,4) NOT NULL, trade_date DATE NOT NULL, status VARCHAR(20) NOT NULL, created_at TIMESTAMP, modified_at TIMESTAMP, CONSTRAINT fk_trade_counterparty FOREIGN KEY (counterparty_id) REFERENCES counterparty (id), CONSTRAINT fk_trade_instrument FOREIGN KEY (instrument_id) REFERENCES instruments (id))");
        jdbcTemplate.execute("CREATE TABLE trades_aud (id BIGINT NOT NULL, rev BIGINT NOT NULL, revtype SMALLINT NOT NULL, trade_ref VARCHAR(30), counterparty_id BIGINT, instrument_id BIGINT, quantity DECIMAL(18,4), price DECIMAL(18,4), trade_date DATE, status VARCHAR(20), created_at TIMESTAMP, modified_at TIMESTAMP, PRIMARY KEY (id, rev), CONSTRAINT fk_trades_aud_rev FOREIGN KEY (rev) REFERENCES revinfo (rev))");
    }

    @org.junit.jupiter.api.AfterEach
    void tearDownSchema() {
        jdbcTemplate.execute("DROP TABLE IF EXISTS trades_aud");
        jdbcTemplate.execute("DROP TABLE IF EXISTS instruments_aud");
        jdbcTemplate.execute("DROP TABLE IF EXISTS counterparty_aud");
        jdbcTemplate.execute("DROP TABLE IF EXISTS trades");
        jdbcTemplate.execute("DROP TABLE IF EXISTS instruments");
        jdbcTemplate.execute("DROP TABLE IF EXISTS counterparty");
        jdbcTemplate.execute("DROP TABLE IF EXISTS revinfo");
    }

    @Test
    void tracksInsertAndEachUpdateAsAnEnversRevision() {
        Long tradeId = persistTradeWithThreeUpdates();

        List<Number> revisions = tradeHistoryService.revisionsFor(tradeId);
        assertThat(revisions).hasSize(4);

        Trade snapshot = tradeHistoryService.snapshotAt(tradeId, revisions.get(2));
        assertThat(snapshot.getQuantity()).isEqualByComparingTo("12.0000");

        Trade latestSnapshot = tradeHistoryService.snapshotAt(tradeId, revisions.get(3));
        assertThat(latestSnapshot.getQuantity()).isEqualByComparingTo("13.0000");

        Trade initialSnapshot = tradeHistoryService.snapshotAt(tradeId, revisions.get(0));
        assertThat(initialSnapshot.getQuantity()).isEqualByComparingTo("10.0000");
    }

    private Long persistTradeWithThreeUpdates() {
        Long tradeId;

        EntityManager initialEm = entityManagerFactory.createEntityManager();
        EntityTransaction tx = initialEm.getTransaction();
        tx.begin();
        Counterparty counterparty = new Counterparty("ACME");
        Instrument instrument = new Instrument("AAPL");
        initialEm.persist(counterparty);
        initialEm.persist(instrument);
        Trade trade = new Trade("T-100", counterparty, instrument, BigDecimal.TEN, BigDecimal.ONE, LocalDate.now());
        initialEm.persist(trade);
        tx.commit();
        initialEm.close();

        tradeId = trade.getId();

        for (int i = 1; i <= 3; i++) {
            EntityManager updateEm = entityManagerFactory.createEntityManager();
            EntityTransaction updateTx = updateEm.getTransaction();
            updateTx.begin();
            Trade managedTrade = updateEm.find(Trade.class, tradeId);
            managedTrade.setQuantity(new BigDecimal("10.0000").add(BigDecimal.valueOf(i)));
            updateEm.merge(managedTrade);
            updateTx.commit();
            updateEm.close();
        }

        return tradeId;
    }

    @Configuration
    @EnableAutoConfiguration
    @EntityScan(basePackages = "com.dbtraining.reconx.domain")
    @EnableJpaAuditing
    static class TestConfig {
        @Bean
        TradeHistoryService tradeHistoryService(EntityManager entityManager) {
            return new TradeHistoryService(entityManager);
        }
    }
}
